name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDQ4NTZkZjQtM2I3ZS00M2IwLTkwZjYtOTExMjE5OTY3ZDI5IiwidGVuYW50X2lkIjoiOTg0ZDAwZDA5ZTgwZDEzMTYzYjdiZGU2MWJmNzUxYzgxNWQxN2M4ZThhNWQ2ZGU0NzY2OTQ5OTc2MjliZmM3NiIsImludGVybmFsX3NlY3JldCI6IjkxNDFiZTIxLTUxYzYtNGQ0Yi1hZDkxLWQ1YTc0Y2ExMGM1NyJ9.CgqUS89xwE-_gmPOsBjQGjzEqWj-2zPAiycsI5mZX-Y"
JWT_SECRET = "1234"