name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWQ4NmM5YjQtZGI4Zi00ZTE1LTg4MjgtYmI3YTdlZDQ3ZDQ5IiwidGVuYW50X2lkIjoiOTg0ZDAwZDA5ZTgwZDEzMTYzYjdiZGU2MWJmNzUxYzgxNWQxN2M4ZThhNWQ2ZGU0NzY2OTQ5OTc2MjliZmM3NiIsImludGVybmFsX3NlY3JldCI6IjkxNDFiZTIxLTUxYzYtNGQ0Yi1hZDkxLWQ1YTc0Y2ExMGM1NyJ9.JKshu7-cc4a73UrGD6Nt0r00TvmotV48j6w474us3Pg"
JWT_SECRET="1234"